// import { Geist, Geist_Mono } from "next/font/google";
import { Space_Grotesk, JetBrains_Mono } from "next/font/google";
import "./globals.css";
import CustomCursor from "../components/CustomCursor";
import Navbar from "../components/Navbar";
import BackgroundGlow from "../components/BackgroundGlow";
import SmoothScroll from "../components/SmoothScroll";


import { Inter, Roboto_Mono } from "next/font/google";


import { Plus_Jakarta_Sans, Fira_Code } from "next/font/google";

const jakarta = Plus_Jakarta_Sans({
  variable: "--font-jakarta",
  subsets: ["latin"],
});

const firaCode = Fira_Code({
  variable: "--font-mono",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const robotoMono = Roboto_Mono({
  variable: "--font-mono",
  subsets: ["latin"],
});

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

const spaceGrotesk = Space_Grotesk({
  variable: "--font-space",
  subsets: ["latin"],
});

const jetbrainsMono = JetBrains_Mono({
  variable: "--font-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Oyee Olagoke — Full Stack Engineer & AI Engineer",
  description: "Generated by create next app",
  icons: {
    icon: "https://api.dicebear.com/10.x/micah/svg?seed=theoyee&backgroundColor=121212&radius=150", // <-- Add your link here
  }
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${jakarta.variable} ${firaCode.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col relative overflow-x-hidden scroll-smooth">
        <CustomCursor />
        <BackgroundGlow />
        <SmoothScroll />
        <Navbar />
        {children}
      </body>
    </html>
  );
}